---
title: "Tidy Data"
author: "Rosemary O'Connor"
date: "19 June 2019"
output: html_document
---

```{r}
library(tidyverse)     ## install.packages("tidyverse")
```

```{r}

## read gapminder csv. Note the readr:: prefix identifies which package it's in

gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

```
```{r}
## explore the gapminder dataset
gapminder # this is super long! Let's inspect in different ways
head(gapminder) # shows first 6
tail(gapminder) # shows last 6

head(gapminder, 10) # shows first X that you indicate
tail(gapminder, 12) # guess what this does!

str(gapminder) # ?str - displays the structure of an object
names(gapminder)
dim(gapminder)    # ?dim dimension
ncol(gapminder)   # ?ncol number of columns
nrow(gapminder)   # ?nrow number of rows

summary(gapminder)

library(skimr) # install.packages('skimr')
skim(gapminder)

gapminder$lifeExp # very long! hard to make sense of...
head(gapminder$lifeExp) # can do the same tests we tried before
str(gapminder$lifeExp) # it is a single numeric vector
summary(gapminder$lifeExp) # same information, formatted slightly differently
```

Look at individual dataframe variables
```{r}
# show me the life exp column
gapminder$lifeExp

#using filter to get rows

filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
x <- filter(gapminder, country == "Brazil", year > 1986)  
mean(x$lifeExp) 
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru"))
filter(gapminder, country == "Mexico", year == 2002)

# using select for multiple columns
select(gapminder, year, country, lifeExp) 

# using select to deselect columns
select(gapminder, -continent, -lifeExp) # you can use - to deselect columns

x <- filter(gapminder, country == "Brazil", year > 1986)  
mean(x$lifeExp) 

```

```{r}
select(gapminder, year, country, lifeExp) 
select(gapminder, -continent, -lifeExp) # you can use - to deselect columns

#select and filter together

gap_cambodia  <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp) 

```

```{r}
# Pipes
gapminder %>% head()
gapminder %>% head(3)
## ...we can do this
gap_cambodia  <- gapminder %>% filter(country == "Cambodia")
gap_cambodia2 <- gap_cambodia %>% select(-continent, -lifeExp) 
gap_cambodia  <- gapminder %>% 
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp) 
```
```{r}
# mutate examples
gapminder %>%
  mutate(gdp = pop * gdpPercap)

#Calculate the population in thousands for all Asian #countries in the year 2007 and add it as a new column.

gapminder %>%
  filter(continent == "Asia",
         year == 2007) %>%
  mutate(pop_thousands = pop/1000) %>%
  select(country, year, pop_thousands) #this cleans up the dataframe but isn't necessary


```




