---
title: "TidyCoral"
author: "Rosemary O'Connor"
date: "19 June 2019"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
# install libraries
library(tidyverse) # install.packages("tidyverse")
library(janitor)   # install.packages("janitor")
library(skimr)     # install.packages("skimr")
library(stringr) # added when we needed it for benthic data

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'

#load benthic data

benthic_raw <- read_csv(benthic_url)
head(benthic_raw) 

# Clean up column headers using janitor
## the `janitor` package's `clean_names` function
## often use name of package on non-common functions/packages

benthic <- benthic_raw %>%
  janitor::clean_names()

names(benthic)

#look at some of the headers
benthic <- benthic %>%
  select(id_name, point, x, y, id_date)

head(benthic)

# remove leading special characters that cause problems
benthic <- benthic %>%
  mutate(date = stringr::str_remove_all(id_date, "#"))

# summary stats
summary(benthic)

skimr::skim(benthic)

# look at unique species represented
unique(benthic$id_name)

# quick ggplot

ggplot(benthic, aes(date, fill = id_name)) +
         geom_bar()

```

```{r}
## Load and process Buoy Data

buoy <- readr::read_csv(buoy_url)
head(buoy) # hmm this doesn't look right! Why not? 
#- it is a .txt file

## read_table
buoy_raw <- read_table(buoy_url)
head(buoy) ## still not quite right -- missed some columns. 

## read_table2
buoy_raw <- read_table2(buoy_url)
head(buoy_raw) ## this is what we need!


## this just wasn't the right approach
buoy_test <- read_delim(buoy_url, delim = " ", trim_ws = TRUE, skip=1)

```
```{r}
## The better way to do this - but breaks as no local csv file

#buoy_test <- read_lines(buoy_url)
#y <- buoy_test %>%
#  as_data_frame() %>%
#  mutate(value = str_replace_all(value, ' +', ',')) 
#write_delim(y, 'data/buoy_local_copy.csv')
#
#z <- read_csv('data/buoy_local_copy.csv', skip=1)
#head(z) ## PRAISE BE

```
```{r}
# Now some fun
buoy <- buoy_raw
names(buoy)
head(buoy)

# need to follow the notes in the tutorial for what this does

## 1. overwrite column names
names(buoy) <- str_c(names(buoy),                  ## current header
                  buoy %>% filter(`#YY` == "#yr"), ## row1 -- don't say buoy[1,] 
                  sep = "_")                       ## separate by `_`

## inspect
names(buoy) ## Looks a lot better

## 2. clean up a bit more to get rid of the `#`s and the `/`s. 
names(buoy) <- str_replace_all(names(buoy), "#", "")  # replace `#` with nothing 
names(buoy) <- str_replace_all(names(buoy), "/", "_") # replace `/` with `_`

## inspect to make sure it worked
names(buoy)

## 3. remove redundant row with units
buoy <- buoy %>%
  filter(YY_yr != "#yr")
head(buoy)
buoy <- buoy %>%
  filter(YY_yr != "#yr")
```
```{r}
# Temperature Plot
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar()

## I googled how to rotate the tick label axis so that we can read the labels:
ggplot(buoy, aes(WTMP_degC)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90))

# convert temps to numeric
buoy <- buoy %>% mutate(WTMP_degC = as.numeric(WTMP_degC))

head(benthic)
head(buoy)

# fix date format

buoy <- buoy %>%
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

head(buoy)

```




